name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar JDK
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17' # Ajustar según la versión de Java
        distribution: 'temurin'

    # 3. Instalar dependencias y compilar
    - name: Build with Maven
      run: mvn clean install

    # 4. Ejecutar pruebas
    - name: Run tests
      run: mvn test

    # 5. Verificar calidad del código
    - name: Run Checkstyle
      run: mvn checkstyle:check

    # 6. Generar reporte de cobertura
    - name: Generate Coverage Report
      run: mvn jacoco:report

    # 7. Subir reporte de cobertura
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: target/site/jacoco/index.html
