name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 0. Check versions
      - name: Check versions
        run: |
          mvn -version
          java --version

      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Java 21
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Verificar la versión de Java
      - name: Verify Java version
        run: java --version

      # 4. Instalar Maven (opcional, ya está instalado en ubuntu-latest)
      # Puedes eliminar este paso si no es necesario.
      - name: Install Maven
        run: sudo apt-get install -y maven

      # 5. Verificar la versión de Maven
      - name: Check Maven version
        run: mvn -version

      # 6. Ejecutar Checkstyle
      - name: Run Checkstyle
        run: mvn checkstyle:check

      # 7. Construir el proyecto y compilar
      - name: Build with Maven
        run: mvn clean install

      # 8. Ejecutar pruebas
      - name: Run tests
        run: mvn test

      # 9. Generar reporte de cobertura con JaCoCo
      - name: Generate Coverage Report
        run: mvn jacoco:report
